// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/Banner-babaner/proxytools_nice/cache/entity"
	mock "github.com/stretchr/testify/mock"
)

// CacheRepository is an autogenerated mock type for the CacheRepository type
type CacheRepository struct {
	mock.Mock
}

// Clear provides a mock function with no fields
func (_m *CacheRepository) Clear() {
	_m.Called()
}

// Delete provides a mock function with given fields: key
func (_m *CacheRepository) Delete(key string) {
	_m.Called(key)
}

// DeleteByPattern provides a mock function with given fields: pattern
func (_m *CacheRepository) DeleteByPattern(pattern string) (int, error) {
	ret := _m.Called(pattern)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPattern")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(pattern)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(pattern)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pattern)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteByPrefix provides a mock function with given fields: prefix
func (_m *CacheRepository) DeleteByPrefix(prefix string) int {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPrefix")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// DeleteByTag provides a mock function with given fields: tag
func (_m *CacheRepository) DeleteByTag(tag string) int {
	ret := _m.Called(tag)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTag")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(tag)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Get provides a mock function with given fields: key
func (_m *CacheRepository) Get(key string) (*entity.CacheEntry, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *entity.CacheEntry
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (*entity.CacheEntry, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(string) *entity.CacheEntry); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CacheEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// Set provides a mock function with given fields: key, entry
func (_m *CacheRepository) Set(key string, entry *entity.CacheEntry) {
	_m.Called(key, entry)
}

// Stats provides a mock function with no fields
func (_m *CacheRepository) Stats() entity.CacheStats {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 entity.CacheStats
	if rf, ok := ret.Get(0).(func() entity.CacheStats); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.CacheStats)
	}

	return r0
}

// NewCacheRepository creates a new instance of CacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheRepository {
	mock := &CacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
