// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/Banner-babaner/proxytools_nice/ipfilter/entity"
	mock "github.com/stretchr/testify/mock"
)

// IPCache is an autogenerated mock type for the IPCache type
type IPCache struct {
	mock.Mock
}

// Get provides a mock function with given fields: ip
func (_m *IPCache) Get(ip string) (entity.ListType, bool, bool) {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 entity.ListType
	var r1 bool
	var r2 bool
	if rf, ok := ret.Get(0).(func(string) (entity.ListType, bool, bool)); ok {
		return rf(ip)
	}
	if rf, ok := ret.Get(0).(func(string) entity.ListType); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(entity.ListType)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) bool); ok {
		r2 = rf(ip)
	} else {
		r2 = ret.Get(2).(bool)
	}

	return r0, r1, r2
}

// Remove provides a mock function with given fields: ip
func (_m *IPCache) Remove(ip string) {
	_m.Called(ip)
}

// Set provides a mock function with given fields: ip, listType, hasRule
func (_m *IPCache) Set(ip string, listType entity.ListType, hasRule bool) {
	_m.Called(ip, listType, hasRule)
}

// NewIPCache creates a new instance of IPCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPCache {
	mock := &IPCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
