// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/Banner-babaner/proxytools_nice/ipfilter/entity"
	mock "github.com/stretchr/testify/mock"
)

// IPListRepository is an autogenerated mock type for the IPListRepository type
type IPListRepository struct {
	mock.Mock
}

// GetLists provides a mock function with no fields
func (_m *IPListRepository) GetLists() entity.ListsConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLists")
	}

	var r0 entity.ListsConfig
	if rf, ok := ret.Get(0).(func() entity.ListsConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.ListsConfig)
	}

	return r0
}

// Insert provides a mock function with given fields: cidr, listType
func (_m *IPListRepository) Insert(cidr string, listType entity.ListType) error {
	ret := _m.Called(cidr, listType)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, entity.ListType) error); ok {
		r0 = rf(cidr, listType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertRange provides a mock function with given fields: startIP, endIP, listType
func (_m *IPListRepository) InsertRange(startIP string, endIP string, listType entity.ListType) error {
	ret := _m.Called(startIP, endIP, listType)

	if len(ret) == 0 {
		panic("no return value specified for InsertRange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, entity.ListType) error); ok {
		r0 = rf(startIP, endIP, listType)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoadLists provides a mock function with given fields: lists
func (_m *IPListRepository) LoadLists(lists entity.ListsConfig) {
	_m.Called(lists)
}

// Remove provides a mock function with given fields: ip
func (_m *IPListRepository) Remove(ip string) {
	_m.Called(ip)
}

// Search provides a mock function with given fields: ip
func (_m *IPListRepository) Search(ip string) (entity.ListType, bool) {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 entity.ListType
	var r1 bool
	if rf, ok := ret.Get(0).(func(string) (entity.ListType, bool)); ok {
		return rf(ip)
	}
	if rf, ok := ret.Get(0).(func(string) entity.ListType); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(entity.ListType)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(ip)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// NewIPListRepository creates a new instance of IPListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIPListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IPListRepository {
	mock := &IPListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
