// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	entity "github.com/Banner-babaner/proxytools_nice/ratelimit/entity"
	mock "github.com/stretchr/testify/mock"
)

// RateLimitRepository is an autogenerated mock type for the RateLimitRepository type
type RateLimitRepository struct {
	mock.Mock
}

// Allow provides a mock function with given fields: ip
func (_m *RateLimitRepository) Allow(ip string) bool {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// DecrementConnections provides a mock function with given fields: ip
func (_m *RateLimitRepository) DecrementConnections(ip string) {
	_m.Called(ip)
}

// GetStats provides a mock function with given fields: ip
func (_m *RateLimitRepository) GetStats(ip string) *entity.RateLimitStats {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 *entity.RateLimitStats
	if rf, ok := ret.Get(0).(func(string) *entity.RateLimitStats); ok {
		r0 = rf(ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RateLimitStats)
		}
	}

	return r0
}

// IncrementConnections provides a mock function with given fields: ip
func (_m *RateLimitRepository) IncrementConnections(ip string) bool {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for IncrementConnections")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewRateLimitRepository creates a new instance of RateLimitRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRateLimitRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RateLimitRepository {
	mock := &RateLimitRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
